[workspace]
resolver = "3"
members = [
  "netlink-bindings",
  "netlink-socket",
  "reverse-lookup",
  "codegen",
  "ip-route",
  "ip-route/syntax",
  "ip-route/proc-macro",
  "strip-async",
]

[workspace.package]
version = "0.3.4"

[workspace.dependencies]
netlink-bindings = { path = "./netlink-bindings" }
netlink-socket2 = { path = "./netlink-socket" }
# netlink-bindings = "0.3"
# netlink-socket2 = "0.3"

ip-route = { path = "./ip-route" }
ip-route-syntax = { path = "./ip-route/syntax" }
ip-route-proc-macro = { path = "./ip-route/proc-macro" }
# ip-route-syntax = "0.3"
# ip-route-proc-macro = "0.3"

reverse-lookup = { path = "./reverse-lookup" }
strip-async = { path = "./strip-async" }
